### ISSUE TITLE
Cobblestone turns into Gravel

### ISSUE THREAD

**Issue by Flogah** [chaottic/awokenworld#1]
I assume this is an intended feature, but would it be possible to disable the change from cobblestone to gravel? It can really mess with ceilings and arches in particular and sticks out, unlike mossy cobble surrounded by regular cobblestone.

**Comment by chaottic** [comment]
Yes the cobble to gravel is an intended feature, and is being replaced. As of now there is no config file, but one will be added to: enable, disable, and change the tick rates.
